version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ess_portal_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ess_portal
    ports:
      - '9488:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ess_network

  # MinIO Object Storage
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9894:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "StrongPassword@123"
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - ess_network
volumes:
  postgres_data:
    driver: local

networks:
  ess_network:
    driver: bridge
